### ISSUE TITLE
redundant sub-menu

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#10]
lets keep the submenu hidden for now.  We're not using the "style" and searching by artist and venue is less necessary without 40 clubs of shows

**Comment by andrewfn** [comment]
ok done.
I'll look at just showing calendar and date

**Comment by andrewfn** [comment]
Updated the search bar with no instruments or style. It seems to work well.
I can add the video link whenever you have something ready to show.

**Comment by brianblain** [comment]
let's take off audio too - there's only a few tracks and there won't be any more added

**Comment by andrewfn** [comment]
I can take it off, but even with only a few tracks, I think it's a neat feature for people deciding which concert to go to. I certainly find it useful.
Any reason you won't be adding more?

**Comment by brianblain** [comment]
youtube seemed to be all we need.  I have a volunteer who's keen to populate the audio....stand by
