### ISSUE TITLE
CRITICAL ISSUE the jazz.to domain expired yesterday

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2017#14]
We won't have a mobile site unless we pay the $50 immediately
pay here:
https://www.tonic.to/renewal.htm

**Comment by brianblain** [comment]
Congratulations!

The registration for the domain name, jazz.to, has been renewed! You will soon receive email confirming that your credit card was successfully charged. The registration will next expire on:
Mon Apr 02 02:32:20 2018

**Comment by andrewfn** [comment]
Great!

**Comment by brianblain** [comment]
can you make sure I get a copy of that invoice so I can recover from the office
