### ISSUE TITLE
next tues 10am - final batch of announcements

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#19]
we'll be bumping up to 4 rows on the home page and some other changes I started making - I'll probably have some more changes at end of day

**Comment by andrewfn** [comment]
I've just set the home page to 4 rows

**Comment by andrewfn** [comment]
Check out the test site at:
http://test.torontojazz.com
Let me know when to refresh it.

**Comment by andrewfn** [comment]
The test site is looking good to me.
I still have to do the printable version of the 'at a glance" but I won't be able to do that till later today.
