### ISSUE TITLE
Web header changes

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2017#2]
Looks good. I'll let you know if there are any problems @mplmnt

>can we please replace the jazz header's date box and rotating image with the ones attached here.
While we are at it we should also change the mobile header to reflect the new dates accross the board.
I will change the dates on an other corresponding pages.
I have attached all the necessary files, please let me know if there are any issues.
I am sure there will be homepage changes coming from Brian and Anna in the near future as well.

**Comment by andrewfn** [comment]
New images are up.
You might have to clear your cache to see them.

**Comment by mplmnt** [comment]
The mobile header and coming soon images are working fine.
The datebox2017.png however is not displaying… numerous machines, all clear caches…can we look into it?

thank you

**Comment by andrewfn** [comment]
You are correct. I had flushed the cloud cache but it had not completed.
I have made sure this time it completed and now I get the new datebox.
Thanks for spotting that.

**Comment by mplmnt** [comment]
Now it is loading, thank you!

## 

## Dragan Grubesic

##  visual communications design

 416-333-0408 / mplmnt.com http://www.mplmnt.com/
