### ISSUE TITLE
add series name

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2017#26]
On the backend, on the Edit Concert page, to the Series dropdown, please add:

TD Emerging Artist

(I could not find where to do that myself)

**Comment by andrewfn** [comment]
I've added it.
It requires a deep level of access, so don't worry, you wouldn't have found it.

**Comment by joshgrossman** [comment]
Thanks.  Is it possible to sort/search by series title?  I’ve just tagged a whack of concerts with the new tag - is it possible to bring them all up on one page?

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

**Comment by andrewfn** [comment]
This is a quick and dirty way (using the built-in search)
http://torontojazz.com/search/node/type%3Aconcert%20%22TD%20Emerging%20Artist%22

If you wanted people to be able to search by series like they can by date, it would be a bit more work but it could be done.

**Comment by joshgrossman** [comment]
Quick and dirty is good for now - thanks.

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27
