### ISSUE TITLE
unhide ad's guide to jazz

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2017#28]
Hi Andrew - I'm committing to regular posts to the AD's Guide to Jazz again this year.  Can you please add them back to the home page?  I've posted my first entry:  http://torontojazz.com/guide/seriously-harp-and-piano-duo.

The box should appear beneath the "Latest Blog Post" box and above the "Latest News" box.

Thanks.

Josh

**Comment by andrewfn** [comment]
I've re-enabled it in the location you asked for.
Let me know if there are any more changes needed.
