### ISSUE TITLE
change enews sign-up 

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#31]
we have moved the enews to mailchimp and just sent out the first blast tonight

we need to change the sign-up form and I don't have permissions for that page

here's the embed code from mailchimp (but if you need to get something else, login is enews@tojazz.com and the pass is 82:Bleecker

I'll attach the header to put on the page
![enews-banner](https://user-images.githubusercontent.com/11864078/26859163-dedb8f1a-4b03-11e7-9da6-4f2386cf3e1e.jpg)
![enews-banner](https://user-images.githubusercontent.com/11864078/26859178-f71c105e-4b03-11e7-9249-2466422e8c41.jpg)

:

<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//torontojazz.us15.list-manage.com/subscribe/post?u=e9339cee8af13a3e98f8c189a&amp;id=a08ed8be5c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE3">Address </label>
	<input type="text" value="" name="MMERGE3" class="" id="mce-MMERGE3">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e9339cee8af13a3e98f8c189a_a08ed8be5c" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='MMERGE3';ftypes[3]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by andrewfn** [comment]
Good idea moving to mailchimp.
I should be able to get to this later today.

**Comment by andrewfn** [comment]
I've set it up, and it looks good.
I'm not sure where you wand the header images?
