### ISSUE TITLE
new supplier logo on sponsor page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#33]
this goes below PODS logo - sorry, I was confounded again with this code - logo should link to 

www.vitalCPR.com
![vcpr-rc combined700px](https://user-images.githubusercontent.com/11864078/27098652-5cb9cd7e-5046-11e7-93de-7f2a1bf77054.jpg)

**Comment by andrewfn** [comment]
Done it. (Don't worry -- the sponsor logos are a bit tricky.)
http://torontojazz.com/sponsors
Is that ok, or do you want it lower on the page under PODS?
