### ISSUE TITLE
flickr embed on photo page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#35]
as usual I'm struggling with flickr - I've created a new group for 2017 and now I want to replace the 2016 photos.  The tojazz photos edit page says I do not have permission...

can you take a look - maybe by just replacing the flickr ID we can get it to display the new slideshow

old url was:    www.flickr.com/groups/2891174@N25/pool/

the ID for the new pool is - www.flickr.com/groups/3842718@N22

seems to me we had a little struggle with this last year....

**Comment by andrewfn** [comment]
I've updated it and it seems to work ok.
