### ISSUE TITLE
swap out artistic director's guide with blog

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2017#39]
I'm getting back into weekly blog posts.  With that in mind, on the home page, please REMOVE the "Latest Artistic Directors Guide" box and REPLACE with the "Latest Blog Post" box (which was removed last May).  First blog post here:

http://torontojazz.com/blog/celebration-air

Thanks.

**Comment by andrewfn** [comment]
Hi Josh,
Great to have you blogging again.
I'll get that done before the end of the day.
Best regards.
Andrew

**Comment by andrewfn** [comment]
I've enabled the "Latest Blog Post" box.
Your new post is showing now.
