### ISSUE TITLE
uploading images

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2017#4]
@brianblain said:
> trying to update the "attractions" page  - how to I load up the images to the "images" directory (I guess I have to re-learn these things every year)

No it's not your fault Brian
In the past I have put this page together and have put the images into the "images" directory.
However you can still upload them by using the **File Attachments** on the page.
If you do that, you can access them with something like:
```
<img src="http://jazz.to/sites/default/files/conservatory-170.jpeg" />
```

**Comment by brianblain** [comment]
ok that worked
