### ISSUE TITLE
removing stale content from home page

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2017#40]
As we prepare for our first announcement next week, we'd like to remove stale content from the Latest Blog Posts and Latest News boxes on the left side of the website.  Is it possible to remove from those boxes any content created BEFORE January 1, 2018?  Not delete the content, but just the link in these boxes.

**Comment by andrewfn** [comment]
It's hard to remove content on the basis of date without writing a custom widget.
What is easy to do is to change the number of posts displayed. So I have set it to 1 post for both the blog and the news.
The only issue is that I will have to keep on top of this, increasing the number of posts displayed as you write new posts, so a heads-up would be good.

**Comment by joshgrossman** [comment]
Hi Andrew - just added another blog post, so please increase the number showing in the box to 2.

Thanks!

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Toronto in 2017 (BizBash)

**Comment by andrewfn** [comment]
Done

**Comment by joshgrossman** [comment]
One more - just added another blog post.  Please increase the number showing in the Latest Blog Posts box to three.  Thanks.

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Toronto in 2017 (BizBash)

**Comment by andrewfn** [comment]
Added. No problem!
