### ISSUE TITLE
2018 initial 8 show launch

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2017#41]
We are going on sale with the initial 8 shows this Monday Feb.5th. We will have radio ads going as early as 5am so we should make sure the website is switched over sometime overnight or well before 5am.

Things that will need to change from current state of affairs:
1. Switch homepage to show 9 (really 8) 2018 Festival shows (the concerts have already been built, just not published)
2. New coming soon box with link to a "festival" page which will feature some information on line up announcements. (I will send that imagery later tonight or early tomorrow and will create the page and send link)
3. The "Toronto Jazz Festival 2018" still is still absent from the festival category on the concert page, I know you said you have done this but it is not showing up. If we can look into that please.
4. We will not be changing any of the colours as I previously stated for the time being (phew!) 

I would like to try and get all of it ready for on the dev page for Howard and Patti to approve in the next day or two as it is pretty straight forward.
Please let me know if this all makes sense and if you foresee any issues.

**Comment by andrewfn** [comment]
@mplmnt
- I have added the "Toronto Jazz Festival 2018" category to concerts. I was confused and was thinking you meant the calendar
- As soon as you let me know the festival page is done, I'll clone the main site to dev and make the concerts live on it.
- One question: at what point do you want this festival page linked to the coming soon box. Straight away or on Feb 5th

**Comment by mplmnt** [comment]
- thanks for fixing that
- if it makes it easier I can build the page on the dev site (it will be just an image with a message in text)
- on Feb. 5th no need to change the one there now

should be done with everything in within the hour, updates coming soon

**Comment by mplmnt** [comment]
I have made the page and sent over the new image plus a list of concerts we are announcing

**Comment by andrewfn** [comment]
Take a look at http://dev.jazz.to/
Notes:
- There were only 7 concerts in your list
- You will be able to adjust their order in the normal way, using the "headline" radio buttons in the concert.
- Please remember that any changes to the dev site get blown away every time it is updated. So I had to re-create your festival page on the main site. So in future it's best to put them there but unpublished and I can just publish them on the dev.

**Comment by mplmnt** [comment]
looking good

• somehow omitted the 8th one from the list (sent you it in an email) - please just ad it 
• sounds good as that will most likely need some adjusting
• i will keep this in mind for the future (was trying to save you a step but I guess it was the opposite)

**Comment by andrewfn** [comment]
I see you added the 8th concert. It all looks good to go.
You can preview the public calendar here: http://dev.jazz.to/sites/default/files/calendar.html
I'll probably switch it over just after midnight on Feb 5th

**Comment by mplmnt** [comment]
all looks good ready for Monday morning
I have to take a few sponsors off the sponsor page and deactivate their ads. 
Is it best I do this on the dev page or the current live page? (I can do both if needed)

**Comment by mplmnt** [comment]
Just did it on both so should be all good to go.
Thank you!

**Comment by andrewfn** [comment]
Yes you did the right thing by doing on both since I won't be copying main
to dev before Monday.

**Comment by mplmnt** [comment]
One more last minute request, if possible can we activate the last box to display one more show.
It would be for the special projects ones.

**Comment by andrewfn** [comment]
Done.
b.t.w. if you want a change to show up immediately, you need to clear the
caches:
-top left corner / clear all caches.

That will work for the dev site.
In some instances (mainly images changed) I need to refresh our Cloudflare
distribution network.

**Comment by andrewfn** [comment]
Changes are now live!
