### ISSUE TITLE
remove wishlist from menu

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#5]
I unpublished the wishlist ad and unchecked the wishlist menu item (under Festival) - and I flushed the cache but it is still showing up on menu.  Did I miss something?

**Comment by andrewfn** [comment]
I'm not sure what you did, but the wishlist menu was still checked on this page:
http://torontojazz.com/admin/structure/menu/manage/main-menu

I unchecked the enable box (as you can see) and it's gone from the menu.
Not sure what happened, but no worries, it's gone now.
