### ISSUE TITLE
reassign menu item

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#8]
can you reassign visiting Toronto/dining & nightlife to the following page we created (using a google map!)

http://torontojazz.com/yorkville-dining-nightlife

(there's no edit tabs on the existing restaurants page so looks like you did a little custom work there)

**Comment by andrewfn** [comment]
Yes I did, it's created from our venues list. There's a checkbox that marks a venue as a restaurant. It then got listed on the old restaurants page.
